export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const RELOGIN_START = 'RELOGIN_START'
export const RELOGIN_SUCCESS = 'RELOGIN_SUCCESS'

export const CREATEUSER_START = 'CREATEUSER_START'
export const CREATEUSER_SUCCESS = 'CREATEUSER_SUCCESS'
export const CREATEUSER_FAIL = 'CREATEUSER_FAIL'

export const SAVINGTHEME_START = 'SAVINGTHEME_START'
export const SAVINGTHEME_SUCCESS = 'SAVINGTHEME_SUCCESS'
export const SAVINGTHEME_FAIL = 'SAVINGTHEME_FAIL'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const CLOSEMESSAGE = 'CLOSEMESSAGE'