export const GETTODOLIST_START = 'GETTODOLIST_START'
export const GETTODOLIST_SUCCESS = 'GETTODOLIST_SUCCESS'
export const GETTODOLIST_FAIL = 'GETTODOLIST_FAIL'

export const GETTODOLISTDONE_START = 'GETTODOLISTDONE_START'
export const GETTODOLISTDONE_SUCCESS = 'GETTODOLISTDONE_SUCCESS'
export const GETTODOLISTDONE_FAIL = 'GETTODOLISTDONE_FAIL'


export const ADDTODOITEM_START = 'ADDTODOITEM_START'
export const ADDTODOITEM_SUCCESS = 'ADDTODOITEM_SUCCESS'
export const ADDTODOITEM_FAIL = 'ADDTODOITEM_FAIL'

export const EDITTODOITEM_START = 'EDITTODOITEM_START'
export const EDITTODOITEM_SUCCESS = 'EDITTODOITEM_SUCCESS'
export const EDITTODOITEM_FAIL = 'EDITTODOITEM_FAIL'

export const DELETETODOITEM_START = 'DELETETODOITEM_START'
export const DELETETODOITEM_SUCCESS = 'DELETETODOITEM_SUCCESS'
export const DELETETODOITEM_FAIL = 'DELETETODOITEM_FAIL'

export const CLOSEMESSAGE = 'CLOSEMESSAGE'