export const GETUSERS_START = 'GETUSERS_START'
export const GETUSERS_SUCCESS = 'GETUSERS_SUCCESS'
export const GETUSERS_FAIL = 'GETUSERS_FAIL'

export const DELETEUSER_START = 'DELETEUSER_START'
export const DELETEUSER_SUCCESS = 'DELETEUSER_SUCCESS'
// Pour le snack bar
export const DELETEUSER_RESETSUCCESS = 'DELETEUSER_RESETSUCCESS'
export const DELETEUSER_FAIL = 'DELETEUSER_FAIL'


export const RESETMESSAGE_START = 'RESETMESSAGE_START'