export const GETPROJECTS_START = 'GETPROJECTS_START'
export const GETPROJECTS_SUCCESS = 'GETPROJECTS_SUCCESS'
export const GETPROJECTS_FAIL = 'GETPROJECTS_FAIL'

export const ADDPROJECT_START = 'ADDPROJECT_START'
export const ADDPROJECT_SUCCESS = 'ADDPROJECT_SUCCESS'
export const ADDPROJECT_FAIL = 'ADDPROJECT_FAIL'

export const EDITPROJECT_START = 'EDITPROJECT_START'
export const EDITPROJECT_SUCCESS = 'EDITPROJECT_SUCCESS'
export const EDITPROJECT_FAIL = 'EDITPROJECT_FAIL'

export const DELETEPROJECT_START = 'DELETEPROJECT_START'
export const DELETEPROJECT_SUCCESS = 'DELETEPROJECT_SUCCESS'
export const DELETEPROJECT_FAIL = 'DELETEPROJECT_FAIL'

export const CLOSEMESSAGE = 'CLOSEMESSAGE'

